-- Run this in your Supabase SQL Editor to create the new tables

-- 1. Create the Products Table
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC NOT NULL,
  image_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Insert some sample products
INSERT INTO products (name, category, price, image_url) VALUES
('Organic Chicken Bites', 'Nutrition', 14.99, 'https://lh3.googleusercontent.com/aida-public/AB6AXuCec28e2NkdkTCRa_AFxvf4YHI0YIuo9cLja3OEJtzUg9JGn26R995siSx-bo8Byd3bVDNo1S9v2WlpdO29rUuBZ6jKcCxJT6ugpSKRZ6kLsf159LsdM3vn3DKffeVJW5c0uDfSnTJuTWqMjDrblmn3MWnLxuZN_GgHtGz_86ckpvLn_Z3JKfY2dStX26yM3cRAvwnYv5yhCbpfY9y_fFqW_ju69u17gvnUSpJevNZKUmAHL1CF4n8cdt7lkhV35kwQU_RamTvEybg'),
('Ultra-Tough Rubber Bone', 'Toys', 9.50, 'https://lh3.googleusercontent.com/aida-public/AB6AXuDkL_nxNyv62poXOk8T_Gtumsk_AIZXZ1HkGsF2udJ3QmqQvw1qbNpsie6wQmLNkwGxrlbX9vhpqi4pFnk02gAXirgGZ9bQiVRLfzSkMWSlOH5lkIs5Caf4Lcu9H3EFKiSFoed6-45jRquYmmwescEai6DYFp_ZnqblLSDOfG7uAk1brK-2b23gtInqIvD-KOPZukI-ZrPuJxCoYCfXB5F6fj3EFDM4cRGpqV6hv871SbsDovqHmrvOsdM5ByG3iEE6WiIJ6Rdme5Q'),
('Orthopedic Dream Cloud', 'Bedding', 45.00, 'https://lh3.googleusercontent.com/aida-public/AB6AXuBrRWyy2yQH6gxgFC4iq6UMiiSrJVNLusKLLE2xkt0GYcYNOgZs_XkTNXlXbXwKMGoOapOf09JQCWY9TKbvZo2qNxPycbb5WsFfWeZw7zDKu9DHU392rN7Qj4ncBRBWMk8H6UKELZRLQorYSLYVwdX4cJOCL6hEfEXJS7T4vAPB-PkjdBV_Bu80WC_t0P_-JCcgNrMCDzfLn9VEDT_NolB6uLbIzUiUvi3PVnnszFuzld1CU_LTYCwe1jnl131otG7vJb6tsQprztI'),
('ZenFlow Water Fountain', 'Accessories', 29.99, 'https://lh3.googleusercontent.com/aida-public/AB6AXuCPJNWXUhddUfccUBU_5B_O1hI93s5XHjz4kXp040Pxhde3A65XaBXGu2OdT-w5zVZZqKlS7Cq6-2jDiPqkgpX-JKDEPGjO2YPTUjURkGmN8h-V7TIFaKKq9Wp1imyNVp3DHXfmBk2d_G4j_iliL6DTpeWONdV2xlqJsj7HjMAk7W_B3rzLzmHR41Bft_Aqxxf7x3QkxYaWWGz3osQHRMmuadRUQrX2PPmhV39Z0aAjLmXMnF4CjDTfoQa-5etwwtmRAG_6x1Mv8pY');

-- 2. Create the Appointments Table
CREATE TABLE appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT NOT NULL,
  service_name TEXT NOT NULL,
  status TEXT DEFAULT 'pending' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create the Cart Table
CREATE TABLE cart (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT NOT NULL,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  UNIQUE(user_email, product_id)
);
-- 4. Create the Profiles Table (User Data)
CREATE TABLE zootopiaDatabase (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  first_name TEXT,
  last_name TEXT,
  email TEXT UNIQUE NOT NULL,
  role TEXT DEFAULT 'user' NOT NULL,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);
